function asset_names = Road3Rho5AssetNames_2020()
%ROAD3RHO5ASSETNAMES_2020 Canonical MPC data files copied during activation.

asset_names = { ...
    'prediction_model_front.mat', ...
    'prediction_model_rear.mat', ...
    'mpc_qp_data_front.mat', ...
    'mpc_qp_data_rear.mat', ...
    'regionless_mpc_data_front.mat', ...
    'regionless_mpc_data_rear.mat', ...
    'regionless_mpc_data_front_full.mat', ...
    'regionless_mpc_data_rear_full.mat' ...
};
end
