function regions = NonlinearDamperRegions_2020(cfg)
%NONLINEARDAMPERREGIONS_2020 Piecewise linear Big SUV damper regions.

defs = { ...
    'REB_HIGH',  -1.41, -0.72; ...
    'REB_MID',   -0.72, -0.21; ...
    'LOW',       -0.21,  0.20; ...
    'COMP_MID',   0.20,  0.76; ...
    'COMP_HIGH',  0.76,  1.16  ...
};

rate_m_s = cfg.damper_rate_mm_s(:) / 1000;
force_N = cfg.damper_force_N(:);

regions = struct( ...
    'name', {}, ...
    'v_min_m_s', {}, ...
    'v_max_m_s', {}, ...
    'c_element_N_s_per_m', {}, ...
    'c_front_N_s_per_m', {}, ...
    'c_rear_N_s_per_m', {}, ...
    'fit_rate_m_s', {}, ...
    'fit_force_N', {} ...
);

for i = 1:size(defs, 1)
    name = defs{i, 1};
    v_min = defs{i, 2};
    v_max = defs{i, 3};
    idx = rate_m_s >= v_min & rate_m_s <= v_max & rate_m_s ~= 0;
    assert(nnz(idx) >= 2, 'Damper region %s needs at least two nonzero table points.', name);

    v = rate_m_s(idx);
    f = force_N(idx);
    c_element = sum(v .* f) / sum(v .^ 2);

    regions(i).name = name; 
    regions(i).v_min_m_s = v_min;
    regions(i).v_max_m_s = v_max;
    regions(i).c_element_N_s_per_m = c_element;
    regions(i).c_front_N_s_per_m = c_element * cfg.damper_front_motion_ratio^2;
    regions(i).c_rear_N_s_per_m = c_element * cfg.damper_rear_motion_ratio^2;
    regions(i).fit_rate_m_s = v;
    regions(i).fit_force_N = f;
end
end
