function self_check_2020()
%SELF_CHECK_2020 Lightweight structural checks for the CarSim 2020 setup.

root_dir = fileparts(mfilename('fullpath'));

required_files = { ...
    'config_2020.m', ...
    'Step1_BuildPredictionModel_2020.m', ...
    'Step2_BuildMPCmatrices_2020.m', ...
    'Step3_RegionlessSolver_2020.m', ...
    'Step4_CheckSimulink_2020.m', ...
    'AnalyzeFlatPose_2020.m', ...
    'AnalyzeRoadExperiment_2020.m', ...
    'AnalyzeRoadAcceptance_2020.m', ...
    'AnalyzeRoad3BumpExperiment_2020.m', ...
    'AnalyzeRoad3T2PassiveGap_2020.m', ...
    'ConfigureRoad3Actuator50_2020.m', ...
    'empc_calibration_settings_2020.m', ...
    'fix_simulink_io_2020.m', ...
    'generate_road3_bump_csvs_2020.m', ...
    'road3_actuator50_step_2020.m', ...
    'road3_bump_safe_output_2020.m', ...
    'rear_diff_limiter_2020.m', ...
    'test_calibration_tools_2020.m', ...
    'test_road3_actuator50_2020.m', ...
    'test_road_experiment_tools_2020.m', ...
    'test_road_acceptance_2020.m', ...
    'test_road3_tools_2020.m', ...
    'per_corner_mpc_L1_2020.m', ...
    'per_corner_mpc_R1_2020.m', ...
    'per_corner_mpc_L2_2020.m', ...
    'per_corner_mpc_R2_2020.m', ...
    'regionless_mpc_eval_2020.m', ...
    'untitled_2020.slx' ...
};

for i = 1:numel(required_files)
    file_path = fullfile(root_dir, required_files{i});
    assert(exist(file_path, 'file') > 0, 'Missing required file: %s', file_path);
end

cfg = config_2020();
assert(cfg.dt == 0.001, 'Expected dt=0.001');
assert(cfg.p == 80, 'Expected p=80');
assert(cfg.c == 10, 'Expected c=10');
assert(cfg.N == 20, 'Expected N=20');
assert(cfg.n_x == 26, 'Expected n_x=26');
assert(cfg.rho5_front == cfg.rho5, 'Expected default front rho5 to match cfg.rho5');
assert(cfg.rho5_rear >= cfg.rho5, 'Expected rear rho5 to be at least the base cfg.rho5');
assert(abs(cfg.c1r - 7949.1) < 1.0, 'Unexpected rear equivalent damping');
assert(abs(cfg.c1f - cfg.c1r) < eps, 'Front damping should default to rear damping');

[front_enabled, front_limit] = empc_calibration_settings_2020('L1', 'B1_FRONT_ONLY');
[rear_enabled, rear_limit] = empc_calibration_settings_2020('L2', 'B1_FRONT_ONLY');
assert(front_enabled && front_limit == 9000, 'B1 front calibration settings changed unexpectedly');
assert(~rear_enabled && rear_limit == 0, 'B1 rear calibration settings changed unexpectedly');

[front_enabled, front_limit, ~, front_post] = empc_calibration_settings_2020('L1');
[rear_enabled, rear_limit, ~, rear_post] = empc_calibration_settings_2020('L2');
assert(front_enabled && front_limit == 500 && front_post.enabled && front_post.energy_gate_mode == 0 && front_post.smooth_tau_s == 0, ...
    'Default calibration mode should use strict ACT50 nonlinear front500 output');
assert(~rear_enabled && rear_limit == 0 && ~rear_post.enabled, ...
    'Default nonlinear front500 mode should disable rear output');

[front_enabled, front_limit, ~, front_post] = empc_calibration_settings_2020('L1', 'ROAD3_T2_FRONT_ONLY_TIGHT');
[rear_enabled, rear_limit, ~, rear_post] = empc_calibration_settings_2020('L2', 'ROAD3_T2_FRONT_ONLY_TIGHT');
assert(front_enabled && front_limit == 1000 && front_post.enabled, 'T2 front-only mode should enable front tight output');
assert(~rear_enabled && rear_limit == 0 && ~rear_post.enabled, 'T2 front-only mode should disable rear output');

[~, ~, ~, gate_post] = empc_calibration_settings_2020('L1', 'ROAD3_T2_COMFORT_GATE_UV_POS');
assert(gate_post.enabled && gate_post.energy_gate_mode == 1, 'T2 comfort UV_POS mode should enable the positive energy gate');

[~, ~, ~, best_post] = empc_calibration_settings_2020('L1', 'ROAD3_PAPER_ACTIVE_BEST');
assert(best_post.enabled && best_post.energy_gate_mode == 1, 'Paper active best should alias Q_C + UV_POS output policy');

[front_enabled, front_limit] = empc_calibration_settings_2020('L1', 'B3_CONSERVATIVE');
[rear_enabled, rear_limit] = empc_calibration_settings_2020('L2', 'B3_CONSERVATIVE');
assert(front_enabled && front_limit == 3000, 'B3/B4 front calibration settings changed unexpectedly');
assert(rear_enabled && rear_limit == 2000, 'B3/B4 rear calibration settings changed unexpectedly');

[front_enabled, front_limit, front_scale] = empc_calibration_settings_2020('L1', 'PASSIVE_ZERO');
[rear_enabled, rear_limit, rear_scale] = empc_calibration_settings_2020('L2', 'PASSIVE_ZERO');
assert(~front_enabled && front_limit == 0 && front_scale == 1, 'PASSIVE_ZERO should disable front external force');
assert(~rear_enabled && rear_limit == 0 && rear_scale == 1, 'PASSIVE_ZERO should disable rear external force');

expected_export_order = { ...
    'W1_L1','W1_R1','W1_L2','W1_R2', ...
    'W2_L1','W2_R1','W2_L2','W2_R2', ...
    'Az_SM','Vz_SM', ...
    'Jnc_L1','Jnc_R1','Jnc_L2','Jnc_R2', ...
    'JncR_L1','JncR_R1','JncR_L2','JncR_R2', ...
    'Zgnd_L1','Zgnd_R1','Zgnd_L2','Zgnd_R2', ...
    'Vx','Pitch' ...
};
assert(isequal(cfg.export_order, expected_export_order), 'Unexpected Export order');

fprintf('self_check_2020 passed structural checks.\n');
end
